name: Go

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]

jobs:
  lint_check:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          # skip cache to avoid flakes (and avoid using gh-action storage)
          skip-build-cache: true
          skip-pkg-cache: true


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
